config/routes.rb
Rails.application.routes.draw do

  root 'posts#index', as: 'home'             #home page
  get 'about' => 'pages#about', as: 'about'  #about page

  resources :posts                           #all CRUD routes for posts ^^
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'This is the about page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">
      <%= link_to "SimpleBlog", home_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           <%= link_to "Home", home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Post", new_post_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1 class="h1-small-margin">Edit Post</h1>
<%= form_for(:post, url: post_path(@post), method: :patch, :html => { :style => 'width:50%; margin: 10px;'}) do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1 class="h1-small-margin">Blog Posts</h1>
<% @posts.each do |post| %>
  <div class="card card-body bg-light" style="margin: 30px;">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <p><%= link_to "Read More", post_path(post), class: 'btn btn-secondary' %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="h1-small-margin">Add Post</h1>
<%= form_for(:post, url: posts_path, :html => { :style => 'width:50%; margin: 10px;'}) do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1 class="h1-small-margin"><%= @post.title %></h1>
<p class="card card-body bg-light" style="margin: 30px;"><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), class:'btn btn-secondary' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger' %>